name: Deploy site to GitHub Pages

on:
  push:
    branches:
      - master
      # - source
      # It is highly recommended that you only run this action on push to a
      # specific branch, eg. master or source (if on *.github.io repo)

jobs:
  jekyll:
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch repository
        uses: actions/checkout@v2
        # If you want dates
        # fetch-depth: '0'
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1

      - name: Install Dependencies & Jekyll Build
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          # Reduce repo churn gh-pages will be a branch containing single orphan commit
          force_orphan: true
          user_name: "Open Collaboration"
          user_email: "noreply@opencollab.dev"
          commit_message: "Deploy: "
